### ISSUE TITLE
网站上的字体能否改小一点？

### ISSUE THREAD

**Issue by ghost** [wangdoc/website#2]
我能理解把字体设置得大一点是为了阅读文档时更方便，但这也太大了点，我缩放到 80% 才感觉刚刚好。

目前在用缩放，但是缩放的效果不是很好，页面上的评论字体又显得太小了。

能不能把字体改小一点呢？对于阅读文档来说，比普通的字体稍微大一点就可以了吧？现在浏览器基本都有缩放功能，如果有人看不清的话也可以放大。

**Comment by ruanyf** [comment]
目前，这个两栏式的样式，调小字体会使得一行的文字过多。

以后，修改样式的时候，会考虑小字体的样式。
