### ISSUE TITLE
添加国内镜像

### ISSUE THREAD

**Issue by yb6b** [wangdoc/website#3]
谢谢阮大的无私奉献。Wangdoc的文章质量优秀，可是在国内访问太慢，时而无响应。建议添加国内的镜像。

如果太麻烦，可以在首页和仓库里帖个超链接也可。

**Comment by ruanyf** [comment]
网道用了 Cloudflare 作为免费 CDN，国内有些地区确实可能无法访问，或者访问速度慢。

后面考虑搬回国内，或者加一个镜像，争取今年内解决。
