### ISSUE TITLE
几张封面图，或许您能用得上

### ISSUE THREAD

**Issue by liujuanjuan1984** [wangdoc/website#4]
阮先生，您好。

我是 [xue.cn](https://xue.cn/hub/) 的内容编辑 刘娟娟，我们即将上线 wangdoc 的几份教程作为在线书籍。并为此制作了几张封面。经设计者西乔女士同意，这些封面图特赠予您，或许wangdoc项目这边能用得上。（无版权问题，您可放心使用。）

![cover_bash_tutorial](https://user-images.githubusercontent.com/31027645/112274207-33278b00-8cb9-11eb-9d8e-988b2a61b5de.png)
![cover_es6_tutorial](https://user-images.githubusercontent.com/31027645/112274219-3458b800-8cb9-11eb-8504-01be431f1d29.png)
![cover_html_tutorial](https://user-images.githubusercontent.com/31027645/112274220-34f14e80-8cb9-11eb-9cc2-aedd70d8437f.png)
![cover_ssh_tutorial](https://user-images.githubusercontent.com/31027645/112274226-36227b80-8cb9-11eb-9597-2168cfa56667.png)

以下两份封面是已经上线的小册子/在线书籍封面。

![cover_document_style_guide](https://user-images.githubusercontent.com/31027645/112274539-931e3180-8cb9-11eb-959f-e201f6a8c60f.png)
![cover_javascript_tutorial](https://user-images.githubusercontent.com/31027645/112274623-a9c48880-8cb9-11eb-8a9d-3202ee66e42b.png)

感谢 网道项目和您的贡献。

**Comment by ruanyf** [comment]
封面设计得挺好的。
