### ISSUE TITLE
阮大侠，文档要收录吗

### ISSUE THREAD

**Issue by linjialiang** [wangdoc/website#5]
我自己有在写的文档，最近开始重新整理成一个个知识点小块，阮大侠要不要收录下

文档写的不是很好，你可以看下是否能满足要求

https://gitee.com/linjialiang/wamp-tutorial

**Comment by ruanyf** [comment]
目前阶段，网道主要收录基础语言的文档，不考虑开发文档。

**Comment by linjialiang** [comment]
好吧，阮大侠辛苦了，你的wangdoc对我帮助很大
