### ISSUE TITLE
wangdoc 站点无法打开了

### ISSUE THREAD

**Issue by linjialiang** [wangdoc/website#6]
wangdoc 站点无法打开了

**Comment by linjialiang** [comment]
![图片](https://user-images.githubusercontent.com/8848263/133891179-591c9116-7d6d-437e-a3e2-6bdbd58eb97e.png)

**Comment by ruanyf** [comment]
网道用了 Cloudflare 的免费 CDN，个别节点无法访问，是可能的。

你可以换个时间，或者换个网络服务商再试试。

后面会考虑搬到国内，或做一个镜像。

**Comment by linjialiang** [comment]
电信自带的dns无法正常，114.114.114.114 可以正常访问

**Comment by ruanyf** [comment]
现在还是不行吗？

**Comment by linjialiang** [comment]
现在都可以了
